name: Ezra Bible App test suite

on: push

jobs:
    test:
        name: Run Cucumber tests
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '10'

        - run: sudo apt install -y libcurl4-gnutls-dev xvfb
        - run: npm install
        
        - name: Compile templates
          run: npm run compile-pug
        
        # - name: Bundle JS
          # run: npm run bundle

        - name: Run test
          run: npm run headless-test
          env:
            JOBS: MAX

        - name: Archive screenshot (in case of an error)
          uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: screenshot.png
            path: ./test_screenshot.png